#!/usr/bin/env node
/**
 * Setup for dendrite-admin-mcp.
 *
 * Writes a .env from your answers (or flags), installs dependencies, builds,
 * runs the test suite, and prints the exact MCP registration snippet for your
 * agent (Claude Code, Codex, OpenCode, GitHub Copilot, Pi, ...).
 *
 * Usage:
 *   npm run setup                                  # interactive prompts
 *   npm run setup -- --base-url https://matrix.example.com \
 *     --admin-token <token> [--shared-secret <secret>] \
 *     [--transport stdio|http] [--mcp-token <token>] \
 *     [--skip-install] [--skip-build] [--skip-test]
 *
 * Value resolution order: CLI flag > shell env var > existing .env > prompt.
 * Prompts are skipped when stdin is not a TTY (e.g. when an agent runs this).
 */
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const ENV_FILE = path.join(ROOT, ".env");
const DIST_INDEX = path.join(ROOT, "dist", "index.js");

const REQUIRED_VARS = [
  {
    key: "DENDRITE_BASE_URL",
    flag: "base-url",
    prompt: "Dendrite homeserver base URL (client-facing port, no trailing slash)",
    example: "https://matrix.example.com",
  },
  {
    key: "DENDRITE_ADMIN_TOKEN",
    flag: "admin-token",
    prompt: "Dendrite admin user access token (Bearer token for /_dendrite/admin)",
    example: "syt_... (from your admin user's account)",
  },
];

const OPTIONAL_VARS = [
  {
    key: "DENDRITE_REGISTRATION_SHARED_SECRET",
    flag: "shared-secret",
    prompt: "registration_shared_secret from dendrite.yaml (only needed for register_user)",
    example: "leave blank to skip",
  },
];

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith("--")) continue;
    const eq = a.indexOf("=");
    if (eq !== -1) {
      args[a.slice(2, eq)] = a.slice(eq + 1);
      continue;
    }
    const key = a.slice(2);
    const next = argv[i + 1];
    if (next !== undefined && !next.startsWith("--")) {
      args[key] = next;
      i++;
    } else {
      args[key] = true;
    }
  }
  return args;
}

function readEnvFile(file) {
  const out = {};
  if (!existsSync(file)) return out;
  for (const line of readFileSync(file, "utf8").split("\n")) {
    const m = line.match(/^([A-Z_]+)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function writeEnvFile(file, values) {
  const lines = [
    "# Generated by `npm run setup`. Do not commit this file.",
    `# Dendrite homeserver (client-facing port), no trailing slash.`,
    `DENDRITE_BASE_URL=${values.DENDRITE_BASE_URL}`,
    ``,
    `# Access token of a Dendrite server admin user.`,
    `DENDRITE_ADMIN_TOKEN=${values.DENDRITE_ADMIN_TOKEN}`,
    ``,
    `# Optional: registration_shared_secret from dendrite.yaml. Only needed for`,
    `# the register_user tool (shared-secret registration).`,
    `DENDRITE_REGISTRATION_SHARED_SECRET=${values.DENDRITE_REGISTRATION_SHARED_SECRET ?? ""}`,
    ``,
    `# --- MCP transport ---`,
    `# "stdio" (default): spawned directly by your agent. No network exposure.`,
    `# "http": Streamable HTTP server on MCP_HTTP_HOST:MCP_HTTP_PORT (requires MCP_AUTH_TOKEN).`,
    `MCP_TRANSPORT=${values.MCP_TRANSPORT}`,
    ``,
    `# Required when MCP_TRANSPORT=http. Bearer token gating /mcp.`,
    `MCP_AUTH_TOKEN=${values.MCP_AUTH_TOKEN ?? ""}`,
    ``,
    `# Only used when MCP_TRANSPORT=http.`,
    `MCP_HTTP_HOST=${values.MCP_HTTP_HOST ?? "0.0.0.0"}`,
    `MCP_HTTP_PORT=${values.MCP_HTTP_PORT ?? "3939"}`,
    ``,
  ];
  writeFileSync(file, lines.join("\n"), { mode: 0o600 });
}

function run(cmd, args, opts = {}) {
  const res = spawnSync(cmd, args, { stdio: "inherit", ...opts });
  if (res.error) {
    console.error(`\n[setup] failed to run '${cmd}': ${res.error.message}`);
    process.exit(1);
  }
  if (res.status !== 0) {
    console.error(
      `\n[setup] '${cmd} ${args.join(" ")}' failed (exit ${res.status ?? "signal " + res.signal}).`,
    );
    process.exit(1);
  }
}

function snippetClaudeCode(env) {
  return [
    "# Claude Code — user-scoped (all projects):",
    "claude mcp add --transport stdio --scope user dendrite-admin \\",
    `  --env DENDRITE_BASE_URL=${env.DENDRITE_BASE_URL} \\`,
    `  --env DENDRITE_ADMIN_TOKEN=${env.DENDRITE_ADMIN_TOKEN} \\`,
    `  -- node ${DIST_INDEX}`,
    "",
    "# or project-scoped .mcp.json in this repo (env vars must be exported):",
    JSON.stringify(
      {
        mcpServers: {
          "dendrite-admin": {
            type: "stdio",
            command: "node",
            args: ["${CLAUDE_PROJECT_DIR:-.}/dist/index.js"],
            env: {
              DENDRITE_BASE_URL: "${DENDRITE_BASE_URL}",
              DENDRITE_ADMIN_TOKEN: "${DENDRITE_ADMIN_TOKEN}",
            },
          },
        },
      },
      null,
      2,
    ),
  ].join("\n");
}

function snippetCodex(env) {
  return [
    "# Codex CLI:",
    "codex mcp add dendrite-admin \\",
    `  --env DENDRITE_BASE_URL=${env.DENDRITE_BASE_URL} \\`,
    `  --env DENDRITE_ADMIN_TOKEN=${env.DENDRITE_ADMIN_TOKEN} \\`,
    `  -- node ${DIST_INDEX}`,
    "",
    "# or ~/.codex/config.toml:",
    "[mcp_servers.dendrite-admin]",
    `command = "node"`,
    `args = ["${DIST_INDEX}"]`,
    "enabled = true",
    "",
    "[mcp_servers.dendrite-admin.env]",
    `DENDRITE_BASE_URL = "${env.DENDRITE_BASE_URL}"`,
    `DENDRITE_ADMIN_TOKEN = "${env.DENDRITE_ADMIN_TOKEN}"`,
  ].join("\n");
}

function snippetOpenCode(env) {
  return [
    "# opencode — add to opencode.json (or opencode.jsonc):",
    JSON.stringify(
      {
        $schema: "https://opencode.ai/config.json",
        mcp: {
          "dendrite-admin": {
            type: "local",
            command: ["node", DIST_INDEX],
            environment: {
              DENDRITE_BASE_URL: env.DENDRITE_BASE_URL,
              DENDRITE_ADMIN_TOKEN: env.DENDRITE_ADMIN_TOKEN,
            },
            enabled: true,
          },
        },
      },
      null,
      2,
    ),
    "",
    "# or: opencode mcp add dendrite-admin -- node " + DIST_INDEX,
    "# (opencode v2 nests servers under mcp.servers)",
  ].join("\n");
}

function snippetCopilot(env) {
  return [
    "# GitHub Copilot CLI:",
    "copilot mcp add dendrite-admin \\",
    `  --env DENDRITE_BASE_URL=${env.DENDRITE_BASE_URL} \\`,
    `  --env DENDRITE_ADMIN_TOKEN=${env.DENDRITE_ADMIN_TOKEN} \\`,
    `  -- node ${DIST_INDEX}`,
    "",
    "# or ~/.copilot/mcp-config.json:",
    JSON.stringify(
      {
        mcpServers: {
          "dendrite-admin": {
            type: "local",
            command: "node",
            args: [DIST_INDEX],
            env: {
              DENDRITE_BASE_URL: env.DENDRITE_BASE_URL,
              DENDRITE_ADMIN_TOKEN: env.DENDRITE_ADMIN_TOKEN,
            },
            tools: ["*"],
          },
        },
      },
      null,
      2,
    ),
  ].join("\n");
}

function snippetPi(env) {
  return [
    "# Pi — ~/.pi/agent/mcp.json (global) or .mcp.json in a trusted project:",
    JSON.stringify(
      {
        mcpServers: {
          "dendrite-admin": {
            command: "node",
            args: [DIST_INDEX],
            env: {
              DENDRITE_BASE_URL: env.DENDRITE_BASE_URL,
              DENDRITE_ADMIN_TOKEN: env.DENDRITE_ADMIN_TOKEN,
            },
          },
        },
      },
      null,
      2,
    ),
  ].join("\n");
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const interactive = Boolean(input.isTTY);
  const rl = interactive ? createInterface({ input, output }) : null;

  const ask = async (prompt, current) => {
    if (!rl) return current;
    const answer = await rl.question(`${prompt} [${current || "none"}]: `);
    return answer.trim() || current;
  };

  const existing = readEnvFile(ENV_FILE);

  const resolve = async (key, flag, prompt, example, { optional = false } = {}) => {
    if (args[flag] !== undefined) {
      if (args[flag] === true) {
        throw new Error(`[setup] --${flag} requires a value (got a bare flag).`);
      }
      return String(args[flag]);
    }
    if (process.env[key]) return process.env[key];
    if (existing[key]) return existing[key];
    if (interactive) {
      let answer = "";
      do {
        answer = (await ask(`${prompt} (e.g. ${example})`, "")).trim();
        if (!answer && !optional) {
          console.log(`[setup] ${key} is required — please enter a value.`);
        }
      } while (!answer && !optional);
      return answer;
    }
    if (optional) return undefined;
    throw new Error(
      `[setup] ${key} is required. Pass --${flag} <value>, export ${key}, or run interactively.`,
    );
  };

  console.log(`\n[dendrite-admin-mcp] setup in ${ROOT}\n`);
  if (interactive) {
    console.log(
      "[setup] Note: secret values are echoed as you type (they are also saved to .env).\n",
    );
  }

  // Node version check.
  const nodeMajor = Number(process.versions.node.split(".")[0]);
  if (nodeMajor < 18) {
    console.error(`[setup] Node >= 18 required (found ${process.versions.node}).`);
    process.exit(1);
  }

  // Resolve values.
  const values = {};
  for (const v of REQUIRED_VARS) {
    values[v.key] = await resolve(v.key, v.flag, v.prompt, v.example);
  }
  for (const v of OPTIONAL_VARS) {
    const val = await resolve(v.key, v.flag, v.prompt, v.example, { optional: true });
    if (val) values[v.key] = val;
  }

  values.MCP_TRANSPORT = (args.transport || process.env.MCP_TRANSPORT || existing.MCP_TRANSPORT || "stdio").toLowerCase();
  if (interactive) {
    const answer = await ask(
      "MCP transport (stdio = spawned by your agent, http = network server)",
      values.MCP_TRANSPORT,
    );
    if (answer) values.MCP_TRANSPORT = answer.toLowerCase();
  }
  if (!["stdio", "http"].includes(values.MCP_TRANSPORT)) {
    console.error(`[setup] MCP_TRANSPORT must be 'stdio' or 'http' (got '${values.MCP_TRANSPORT}').`);
    process.exit(1);
  }

  if (values.MCP_TRANSPORT === "http") {
    if (args["mcp-token"] === true) {
      console.error("[setup] --mcp-token requires a value (got a bare flag).");
      process.exit(1);
    }
    values.MCP_AUTH_TOKEN =
      args["mcp-token"] || process.env.MCP_AUTH_TOKEN || existing.MCP_AUTH_TOKEN || randomBytes(32).toString("hex");
    if (interactive) {
      const answer = await ask(
        `MCP_AUTH_TOKEN (bearer token gating /mcp; blank to generate one)`,
        values.MCP_AUTH_TOKEN,
      );
      values.MCP_AUTH_TOKEN = answer || values.MCP_AUTH_TOKEN;
    }
    if (interactive) {
      console.log(`[setup] MCP_AUTH_TOKEN: ${values.MCP_AUTH_TOKEN}`);
    } else {
      console.log("[setup] MCP_AUTH_TOKEN written to .env (read it from there).");
    }
  }

  // Write .env.
  if (existsSync(ENV_FILE)) {
    console.log(`[setup] ${ENV_FILE} already exists — it will be overwritten.`);
  }
  writeEnvFile(ENV_FILE, values);
  console.log(`[setup] wrote ${ENV_FILE}`);

  // Install / build / test.
  if (!args["skip-install"]) {
    const lockfile = existsSync(path.join(ROOT, "package-lock.json"));
    console.log(`[setup] installing dependencies (${lockfile ? "npm ci" : "npm install"})...`);
    run("npm", lockfile ? ["ci"] : ["install"], { cwd: ROOT });
  }
  if (!args["skip-build"]) {
    console.log("[setup] building...");
    run("npm", ["run", "build"], { cwd: ROOT });
  }
  if (!args["skip-test"]) {
    console.log("[setup] running tests...");
    run("npm", ["test"], { cwd: ROOT });
  }

  if (rl) rl.close();

  // Print registration snippets.
  console.log("\n[setup] done. Register the server with your agent:\n");
  console.log(
    "NOTE: the commands below contain live secrets and will be stored in your shell history and\n" +
      "agent config. Prefer the env-var-indirection JSON forms where your agent supports them.\n",
  );
  console.log("--- Claude Code ---\n" + snippetClaudeCode(values) + "\n");
  console.log("--- Codex ---\n" + snippetCodex(values) + "\n");
  console.log("--- opencode ---\n" + snippetOpenCode(values) + "\n");
  console.log("--- GitHub Copilot ---\n" + snippetCopilot(values) + "\n");
  console.log("--- Pi ---\n" + snippetPi(values) + "\n");

  if (values.MCP_TRANSPORT === "http") {
    console.log(
      `[setup] HTTP transport: start with 'npm start', then point clients at http://<host>:${values.MCP_HTTP_PORT ?? "3939"}/mcp with 'Authorization: Bearer <MCP_AUTH_TOKEN>'.`,
    );
  } else {
    console.log(
      `[setup] stdio transport: the registration commands above spawn 'node ${DIST_INDEX}' directly. No server process to keep running.`,
    );
  }
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});